import 'package:equatable/equatable.dart';
import 'category.dart';
import 'transaction.dart';

/// Entity representing transaction form data with validation
class TransactionFormData extends Equatable {
  final String? id; // null for new transaction
  final double? amount;
  final TransactionType type;
  final Category? category;
  final String title;
  final String? description;
  final DateTime date;
  final DateTime? time;

  const TransactionFormData({
    this.id,
    this.amount,
    this.type = TransactionType.expense,
    this.category,
    this.title = '',
    this.description,
    required this.date,
    this.time,
  });

  /// Create form data from existing transaction (for editing)
  factory TransactionFormData.fromTransaction(Transaction transaction) {
    return TransactionFormData(
      id: transaction.id,
      amount: transaction.amount,
      type: transaction.type,
      category: transaction.category,
      title: transaction.title,
      description: transaction.description,
      date: transaction.date,
      time: transaction.date,
    );
  }

  /// Create empty form data (for new transaction)
  factory TransactionFormData.empty() {
    return TransactionFormData(date: DateTime.now());
  }

  /// Validation getters
  bool get isAmountValid => amount != null && amount! > 0;
  bool get isTitleValid => title.trim().isNotEmpty && title.length <= 100;
  bool get isCategoryValid => category != null;
  bool get isDescriptionValid =>
      description == null || description!.isEmpty || description!.length <= 500;
  bool get isDateValid => !date.isAfter(DateTime.now());

  /// Check if all required fields are valid
  bool get isValid =>
      isAmountValid &&
      isTitleValid &&
      isCategoryValid &&
      isDescriptionValid &&
      isDateValid;

  /// Get validation error messages
  String? get amountError {
    if (amount == null) return 'Amount is required';
    if (amount! <= 0) return 'Amount must be greater than zero';
    return null;
  }

  String? get titleError {
    if (title.trim().isEmpty) return 'Title is required';
    if (title.length > 100) return 'Title must be less than 100 characters';
    return null;
  }

  String? get categoryError {
    if (category == null) return 'Category is required';
    return null;
  }

  String? get descriptionError {
    if (description != null && description!.length > 500) {
      return 'Description must be less than 500 characters';
    }
    return null;
  }

  String? get dateError {
    if (date.isAfter(DateTime.now())) {
      return 'Date cannot be in the future';
    }
    return null;
  }

  /// Copy with method
  TransactionFormData copyWith({
    String? id,
    double? amount,
    TransactionType? type,
    Category? category,
    String? title,
    String? description,
    DateTime? date,
    DateTime? time,
  }) {
    return TransactionFormData(
      id: id ?? this.id,
      amount: amount ?? this.amount,
      type: type ?? this.type,
      category: category ?? this.category,
      title: title ?? this.title,
      description: description ?? this.description,
      date: date ?? this.date,
      time: time ?? this.time,
    );
  }

  /// Convert form data to Transaction entity
  Transaction toTransaction() {
    if (!isValid) {
      throw StateError('Cannot convert invalid form data to transaction');
    }

    // Combine date and time if time is provided
    DateTime finalDate = date;
    if (time != null) {
      finalDate = DateTime(
        date.year,
        date.month,
        date.day,
        time!.hour,
        time!.minute,
      );
    }

    return Transaction(
      id: id ?? '', // Will be generated by repository
      title: title.trim(),
      amount: amount!,
      type: type,
      category: category!,
      date: finalDate,
      description: description?.trim(),
    );
  }

  @override
  List<Object?> get props => [
    id,
    amount,
    type,
    category,
    title,
    description,
    date,
    time,
  ];
}
